In [2]:
import pandas as pd
import numpy as np

In [2]:
l=[1,2,3,4,5,6]

In [3]:
arr=np.array(l) # to convert into array there are three type

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
arr1=np.asarray(l)

In [6]:
arr1

array([1, 2, 3, 4, 5, 6])

In [6]:
arr2=np.asanyarray(l)

In [7]:
arr2

array([1, 2, 3, 4, 5, 6])

In [8]:
s=["su","py","mu"]

In [9]:
arr2=np.asanyarray(s)

In [17]:
arr2

array(['su', 'py', 'mu'], dtype='<U2')

In [13]:
l1=[[1,2,3],[4,5,6]]
arr3=np.asanyarray(l1)

In [14]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr.ndim

1

In [18]:
arr2.ndim

1

In [19]:
arr3.ndim

2

In [20]:
type(arr)

numpy.ndarray

In [21]:
type(arr2)

numpy.ndarray

In [22]:
type(arr3)

numpy.ndarray

In [23]:
mat=np.matrix(l)

In [24]:
mat

matrix([[1, 2, 3, 4, 5, 6]])

In [25]:
type(mat)

numpy.matrix

In [28]:
arr

array([1, 2, 3, 4, 5, 6])

In [26]:
a=arr

In [27]:
a

array([1, 2, 3, 4, 5, 6])

In [29]:
a[0]=9

In [30]:
a

array([9, 2, 3, 4, 5, 6])

In [31]:
arr # as both are pointing towards same postion

array([9, 2, 3, 4, 5, 6])

In [34]:
a1=np.copy(arr)

In [35]:
a1

array([9, 2, 3, 4, 5, 6])

In [36]:
arr

array([9, 2, 3, 4, 5, 6])

In [37]:
a1[0]=0

In [38]:
a1 # now u can see it has copied and created a new arry of that element at new place

array([0, 2, 3, 4, 5, 6])

In [39]:
arr

array([9, 2, 3, 4, 5, 6])

In [42]:
np.fromfunction(lambda x,y:x==y,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [43]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [46]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [47]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [48]:
iterable  = (i*i for i in range(5))

In [50]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [53]:
np.fromstring('23 45 56',sep  = ' ' ) # converting from string to inters

array([23., 45., 56.])

In [55]:
np.fromstring('23, 45, 56',sep  = ',' )

array([23., 45., 56.])

In [59]:
print(arr)
print(arr2)
print(arr3)


[9 2 3 4 5 6]
['su' 'py' 'mu']
[[1 2 3]
 [4 5 6]]


In [60]:
arr.size

6

In [61]:
arr2.size

3

In [62]:
arr3.size

6

In [63]:
arr.shape

(6,)

In [64]:
arr2.shape

(3,)

In [65]:
arr3.shape

(2, 3)

In [67]:
arr.dtype

dtype('int64')

In [68]:
arr2.dtype

dtype('<U2')

In [69]:
arr3.dtype

dtype('int64')

In [70]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [71]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [73]:
list(np.arange(.4 , 10.4 , 0.6))

[0.4,
 1.0,
 1.6,
 2.1999999999999997,
 2.8,
 3.4,
 3.9999999999999996,
 4.6000000000000005,
 5.2,
 5.8,
 6.4,
 7.0,
 7.6,
 8.2,
 8.8,
 9.4,
 10.0]

In [74]:
np.linspace(1,5 , 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [75]:
np.logspace(1,5 , 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [76]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [77]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [82]:
np.zeros(5)+3

array([3., 3., 3., 3., 3.])

In [83]:
np.ones(5)+7

array([8., 8., 8., 8., 8.])

In [84]:
np.zeros((3,4,2)) # 3 dimension

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [85]:
np.zeros((3,4,2,2)) # more then 3d but it is an imageable

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [86]:
arr = np.ones((3,4))

In [87]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [92]:
arr+6

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [89]:
a12=arr+6*2

In [90]:
a12

array([[13., 13., 13., 13.],
       [13., 13., 13., 13.],
       [13., 13., 13., 13.]])

In [93]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [94]:
arr1 = np.eye(5)

In [95]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [97]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [100]:
np.random.rand(2,2)

array([[0.74587962, 0.60048333],
       [0.31036356, 0.24417706]])

In [101]:
np.random.randn(2,3)

array([[ 0.82712099, -0.14961378,  0.81572398],
       [ 0.44260885,  0.34359035, -1.04377723]])

In [102]:
arr3 = np.random.randint(1,5 , (3,4))

In [103]:
arr3

array([[4, 1, 3, 4],
       [2, 3, 3, 4],
       [3, 3, 2, 2]])

In [104]:
arr3.size

12

In [105]:
arr3.shape

(3, 4)

In [106]:
arr3.reshape(2,6)

array([[4, 1, 3, 4, 2, 3],
       [3, 4, 3, 3, 2, 2]])

In [107]:
arr3.reshape(6,2)

array([[4, 1],
       [3, 4],
       [2, 3],
       [3, 4],
       [3, 3],
       [2, 2]])

In [108]:
arr3.reshape(4,-1)

array([[4, 1, 3],
       [4, 2, 3],
       [3, 4, 3],
       [3, 2, 2]])

In [109]:
arr3>=3

array([[ True, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True, False, False]])

In [110]:
arr3[arr3>=3]

array([4, 3, 4, 3, 3, 4, 3, 3])

In [111]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [112]:
arr1

array([[1, 1, 2],
       [1, 2, 2],
       [2, 1, 1]])

In [113]:
arr2

array([[1, 2, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [114]:
arr1+arr2

array([[2, 3, 4],
       [2, 3, 3],
       [4, 3, 3]])

In [115]:
arr1-arr2

array([[ 0, -1,  0],
       [ 0,  1,  1],
       [ 0, -1, -1]])

In [116]:
arr1*arr2

array([[1, 2, 4],
       [1, 2, 2],
       [4, 2, 2]])

In [117]:
arr1/arr2

array([[1. , 0.5, 1. ],
       [1. , 2. , 2. ],
       [1. , 0.5, 0.5]])

In [118]:
arr1@arr2 # matrix multiplication

array([[6, 7, 7],
       [7, 8, 8],
       [5, 7, 7]])

In [119]:
arr1

array([[1, 1, 2],
       [1, 2, 2],
       [2, 1, 1]])

In [120]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.41421356],
       [1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.        ]])

In [121]:
np.log10(arr1)

array([[0.     , 0.     , 0.30103],
       [0.     , 0.30103, 0.30103],
       [0.30103, 0.     , 0.     ]])

In [122]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183]])

In [123]:
np.max(arr1)

2

In [124]:
np.min(arr1)

1

In [125]:
arr1

array([[1, 1, 2],
       [1, 2, 2],
       [2, 1, 1]])

In [126]:
arr1.T

array([[1, 1, 2],
       [1, 2, 1],
       [2, 2, 1]])

In [127]:
arr1.flatten()

array([1, 1, 2, 1, 2, 2, 2, 1, 1])

In [128]:
np.expand_dims(arr1,axis=1)

array([[[1, 1, 2]],

       [[1, 2, 2]],

       [[2, 1, 1]]])

In [129]:
np.expand_dims(arr,axis=0)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [3]:
arr = np.random.randint(1,10 , (4,4))

In [4]:
arr

array([[5, 1, 2, 7],
       [2, 4, 8, 7],
       [5, 9, 1, 1],
       [2, 3, 9, 6]])

In [5]:
arr.reshape(8,2)

array([[5, 1],
       [2, 7],
       [2, 4],
       [8, 7],
       [5, 9],
       [1, 1],
       [2, 3],
       [9, 6]])

In [6]:
arr.flatten()

array([5, 1, 2, 7, 2, 4, 8, 7, 5, 9, 1, 1, 2, 3, 9, 6])

In [7]:
np.expand_dims(arr,axis=1)

array([[[5, 1, 2, 7]],

       [[2, 4, 8, 7]],

       [[5, 9, 1, 1]],

       [[2, 3, 9, 6]]])

In [8]:
np.expand_dims(arr,axis=0)

array([[[5, 1, 2, 7],
        [2, 4, 8, 7],
        [5, 9, 1, 1],
        [2, 3, 9, 6]]])

In [9]:
data = np.array([[1] , [2] , [3]])

In [10]:
np.squeeze(data)

array([1, 2, 3])

In [11]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [12]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [13]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [14]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [15]:
arr1

array([[6, 8, 9, 3],
       [1, 7, 9, 2],
       [9, 9, 1, 3]])

In [16]:
arr2

array([[6, 8, 2, 7],
       [2, 5, 9, 5],
       [6, 3, 9, 5]])

In [17]:
arr1**arr2

array([[    46656,  16777216,        81,      2187],
       [        1,     16807, 387420489,        32],
       [   531441,       729,         1,       243]])

In [18]:
arr1

array([[6, 8, 9, 3],
       [1, 7, 9, 2],
       [9, 9, 1, 3]])

In [19]:
arr1>arr2

array([[False, False,  True, False],
       [False,  True, False, False],
       [ True,  True, False, False]])

In [20]:
#Numpy - String Functions.

In [21]:
arr = np.array(["sudh" , "kumar"])

In [22]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [23]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [24]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [25]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [26]:
#Numpy - Mathematical Functions.

In [27]:
arr1

array([[6, 8, 9, 3],
       [1, 7, 9, 2],
       [9, 9, 1, 3]])

In [28]:
np.sin(arr1)

array([[-0.2794155 ,  0.98935825,  0.41211849,  0.14112001],
       [ 0.84147098,  0.6569866 ,  0.41211849,  0.90929743],
       [ 0.41211849,  0.41211849,  0.84147098,  0.14112001]])

In [29]:
np.cos(arr1)

array([[ 0.96017029, -0.14550003, -0.91113026, -0.9899925 ],
       [ 0.54030231,  0.75390225, -0.91113026, -0.41614684],
       [-0.91113026, -0.91113026,  0.54030231, -0.9899925 ]])

In [30]:
np.tan(arr1)

array([[-0.29100619, -6.79971146, -0.45231566, -0.14254654],
       [ 1.55740772,  0.87144798, -0.45231566, -2.18503986],
       [-0.45231566, -0.45231566,  1.55740772, -0.14254654]])

In [31]:
np.log10(arr1)

array([[0.77815125, 0.90308999, 0.95424251, 0.47712125],
       [0.        , 0.84509804, 0.95424251, 0.30103   ],
       [0.95424251, 0.95424251, 0.        , 0.47712125]])

In [32]:
np.exp(arr1)

array([[4.03428793e+02, 2.98095799e+03, 8.10308393e+03, 2.00855369e+01],
       [2.71828183e+00, 1.09663316e+03, 8.10308393e+03, 7.38905610e+00],
       [8.10308393e+03, 8.10308393e+03, 2.71828183e+00, 2.00855369e+01]])

In [34]:
np.power(arr1,2)

array([[36, 64, 81,  9],
       [ 1, 49, 81,  4],
       [81, 81,  1,  9]])

In [36]:
np.mean(arr1)

5.583333333333333

In [37]:
np.max(arr1)

9

In [38]:
np.min(arr1)

1

In [41]:
np.median(arr1)

6.5

In [42]:
np.std(arr1)

3.200477394945253

In [43]:
np.var(arr1)

10.243055555555555

In [44]:
##Sort, Search & Counting Functions.

In [45]:
arr = np.array([4,2,8,5,3,9,12,56])

In [46]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [47]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [48]:
np.searchsorted(arr,6)

5

In [49]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [50]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [51]:
np.count_nonzero(arr1)

6

In [52]:
np.where(arr1 > 0 )

(array([1, 2, 3, 4, 5, 9]),)

In [53]:
np.extract(arr1 >2,arr1)

array([324, 645,  65,   6,   6, 234])

In [54]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [55]:
a = np.copy(arr1)

In [56]:
a

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [57]:
b = arr1.view()

In [58]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [59]:
b[0]=3

In [60]:
b

array([  3, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [61]:
arr1

array([  3, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [62]:
a

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])